var data = [
  ["Tồi", "Tốt"],
  ["Gây nghiện nhẹ", "Gây nghiện cao"],
  ["Nóng", "Lạnh"],
  ["Bình thường", "Kỳ quặc"],
  ["Vô màu", "Đầy màu sắc"],
  ["Ít calo", "Nhiều calo"],
  ["Cảm thấy tồi", "Cảm thấy tốt"],
  ["Không cần thiết", "Cần thiết"],
  ["Rẻ", "Đắt"],
  ["Vũ khí bị đánh giá thấp", "Vũ khí được đánh giá cao"],
  ["Hiếm", "Phổ biến"],
  ["Biểu tượng cảm xúc không hấp dẫn", "Biểu tượng cảm xúc gợi cảm"],
  ["Môn học dễ", "Môn học khó"],
  ["Không được biết đến", "Nổi tiếng"],
  ["Khó sử dụng", "Dễ sử dụng"],
  ["Mệt mỏi", "Tỉnh táo"],
  ["Bẩn", "Sạch"],
  ["Yêu cầu may mắn", "Yêu cầu kỹ năng"],
  ["Vô vị", "Có hương vị"],
  ["Chủ đề nhạt nhẽo", "Chủ đề hấp dẫn"],
  ["Diễn viên kém", "Diễn viên giỏi"],
  ["Cơ bản", "Thịnh hành"],
  ["Công việc nguy hiểm", "Công việc an toàn"],
  ["Giả tưởng", "Khoa học viễn tưởng"],
  ["Thường ngày", "Trang trọng"],
  ["Lương thấp", "Lương cao"],
  ["Khô", "Ướt"],
  ["Kỹ năng bị đánh giá thấp", "Kỹ năng được đánh giá cao"],
  ["Bị cấm", "Được khuyến khích"],
  ["Bản tình ca buồn", "Bản nhạc vui tươi"],
  ["Dễ vỡ", "Bền"],
  ["Người mê công nghệ", "Người lập dị"],
  ["Tốt", "Xấu"],
  ["Ngày tồi tệ nhất trong năm", "Ngày tốt nhất trong năm"],
  ["Thói quen xấu", "Thói quen tốt"],
  ["Người thích mèo", "Người thích chó"],
  ["Sở thích bị cấm", "Sở thích được công khai yêu thích"],
  ["Không tài năng", "Có tài năng"],
  ["Tối", "Sáng"],
  ["Diễn viên bị đánh giá thấp", "Diễn viên được đánh giá cao"],
  ["Khó tìm", "Dễ tìm"],
  ["Người đàn ông xấu xí", "Người đàn ông đẹp trai"],
  ["Khó nhớ", "Dễ nhớ"],
  ["Giản dị", "Tinh tế"],
  ["Không tốt cho sức khỏe", "Tốt cho sức khỏe"],
  ["Người đàn ông xấu", "Người đàn ông tốt"],
  ["Quan trọng lịch sử", "Không quan trọng lịch sử"],
  ["Trọc lông", "Lông lá"],
  ["Không linh hoạt", "Linh hoạt"],
  ["Thú cưng thông thường", "Thú cưng kỳ lạ"],
  ["Người hướng nội", "Người hướng ngoại"],
  ["Sách hay hơn phim", "Phim hay hơn sách"],
  ["Phim tệ", "Phim tốt"],
  ["Xấu xí", "Đẹp"],
  ["Xảy ra chậm", "Xảy ra đột ngột"],
  ["Công việc", "Sự nghiệp"],
  ["Được yêu thích", "Bị ghét"],
  ["Phía Sáng của Sức Mạnh", "Phía Tối của Sức Mạnh"],
  ["Topping pizza tệ", "Topping pizza ngon"],
  ["Thế giới bất hạnh", "Thế giới hạnh phúc"],
  ["Người trưởng thành", "Người non dạng"],
  ["Sở hữu ít được đánh giá cao", "Sở hữu được đánh giá quá cao"],
  ["Người tàn ác", "Người tốt bụng"],
  ["Phim hành động", "Phim phiêu lưu"],
  ["Hoạt động tinh thần", "Hoạt động thể chất"],
  ["Chủ đề không gây tranh cãi", "Chủ đề gây tranh cãi"],
  ["Nhu cầu", "Sở thích"],
  ["Thức ăn khô", "Thức ăn ướt"],
  ["Sở hữu bình thường", "Sở hữu kỳ lạ"],
  ["Thẳng", "Cong"],
  ["Người xấu", "Người tốt"],
  ["Những năm 80", "Những năm 90"],
  ["Ăn đúng đạo lý", "Ăn sai đạo lý"],
  ["Phim ảnh", "Bộ phim"],
  ["Không bắt buộc", "Bắt buộc"],
  ["Chữ cái ít được đánh giá cao", "Chữ cái được đánh giá quá cao"],
  ["Bình thường", "Phi thường"],
  ["Khó phát âm", "Dễ phát âm"],
  ["Chất lượng thấp", "Chất lượng cao"],
  ["Động vật không quyến rũ", "Động vật quyến rũ"],
  ["Bình thường", "Hầm hố"],
  ["Có tiếng xấu", "Có tiếng tốt"],
  ["Sản phẩm kém chất lượng", "Sản phẩm tốt"],
  ["Không phải một món sandwich", "Là một món sandwich"],
  ["Nơi yên tĩnh", "Nơi ồn ào"],
  ["Phim hài", "Phim tâm lý"],
  ["Nguy hiểm", "An toàn"],
  ["Có ý nghĩa văn hóa", "Không có ý nghĩa văn hóa"],
  ["Có thể thay thế được", "Không thể thay thế được"],
  [
    "Vận động viên tệ nhất mọi thời đại",
    "Vận động viên vĩ đại nhất mọi thời đại",
  ],
  ["Hình mẫu", "Ảnh hưởng xấu"],
  ["Chuyên ngành vô dụng", "Chuyên ngành hữu ích"],
  ["Bình yên", "Chiến tranh"],
  ["Phim bị đánh giá thấp", "Phim được đánh giá cao"],
  ["Gồ ghề", "Mượt mà"],
  ["Xấu cho sức khỏe", "Tốt cho sức khỏe"],
  ["Tròn", "Nhọn"],
  [
    "Bằng chứng cho rằng Thượng đế tồn tại",
    "Bằng chứng cho rằng Thượng đế không tồn tại",
  ],
  ["Phim buồn", "Phim vui"],
  ["Lãng phí thời gian", "Sử dụng thời gian tốt"],
  ["Động vật đáng sợ", "Động vật dễ thương"],
  ["Phổ biến", "Nổi bật"],
  ["Sống ngắn", "Sống lâu"],
  ["Không ai làm", "Mọi người làm"],
  ["Mùi hôi", "Mùi thơm"],
  ["Star Wars", "Star Trek"],
  ["Đồ ăn nhẹ", "Bữa ăn"],
  ["Công ty ít xấu", "Công ty xấu nhất"],
  ["Mềm", "Cứng"],
  ["Thực phẩm bổ dưỡng", "Ẩm thực cao cấp"],
  ["Vuông", "Tròn"],
  ["Ngon hơn khi nóng", "Ngon hơn khi lạnh"],
  ["Ngớ ngẩn", "Tuyệt vời"],
  ["Thủ công", "Sản xuất đại trà"],
  ["Siêu năng lực tệ", "Siêu năng lực tốt"],
  ["Không hiệu quả", "Hiệu quả"],
  ["Khó tin", "Dễ tin"],
  ["Tồi tệ", "Tinh tế"],
  ["Tạm thời", "Vĩnh viễn"],
  ["Trông giống con người", "Không trông giống con người"],
  ["Có vị không ngon", "Có vị ngon"],
  ["Thể thao", "Trò chơi"],
  ["Không hợp thời", "Hợp thời"],
  ["Người sống xấu nhất", "Người sống tốt nhất"],
  ["Bị đánh giá thấp", "Được đánh giá cao"],
  ["Món ăn bẩn", "Món ăn sạch"],
  ["Không đạo đức", "Đạo đức"],
  ["Món quà xấu", "Món quà tốt"],
  ["Không thời thượng", "Thời thượng"],
  ["Nhà vô địch tự do", "Kẻ khủng bố"],
  ["Không thể tha thứ", "Có thể tha thứ"],
  ["Thất bại", "Kiệt tác"],
  ["Không có hại", "Có hại"],
  ["Gryffindor", "Slytherin"],
  ["Không vệ sinh", "Vệ sinh"],
  ["Nhạc tệ", "Nhạc hay"],
  ["Vô dụng", "Có ích"],
  ["Phim mà Godzilla sẽ phá hoại", "Phim mà Godzilla sẽ cải thiện"],
  ["Không quan trọng", "Quan trọng"],
  ["Dễ viết chính tả", "Khó viết chính tả"],
  ["Tật xấu", "Đức hạnh"],
  ["Nhạc sĩ bị đánh giá thấp", "Nhạc sĩ bị đánh giá cao"],
  ["Hoạt động không được ưa chuộng", "Hoạt động được ưa chuộng"],
  ["Chia tách", "Nguyên bản"],
  ["Không đáng tin cậy", "Đáng tin cậy"],
  ["Dễ chết", "Khó chết"],
  ["Bất ổn định", "Ổn định"],
  ["Động vật tròn", "Động vật nhọn"],
  ["Chương trình TV tệ", "Chương trình TV hay"],
  ["Truyền thống nam tính", "Truyền thống nữ tính"],
  ["Bộ phận cơ thể vô dụng", "Bộ phận cơ thể hữu ích"],
  ["Trào lưu thịnh hành", "Kinh điển"],
  ["Yếu", "Mạnh"],
  ["Cereal kinh tởm", "Cereal ngon"],
  ["Phát minh vô dụng", "Phát minh hữu ích"],
  ["Tự doanh", "Cứng cựa"],
  ["Không phổ biến", "Phổ biến"],
  ["Bạn bè", "Kẻ thù"],
  ["Nhàm chán", "Thú vị"],
  ["Hôi thối xấu xí", "Hôi thối tốt"],
  ["Kẻ ác", "Anh hùng"],
  ["Hoạt động bị đánh giá thấp", "Hoạt động bị đánh giá cao"],
  ["Vô dụng trong trường hợp khẩn cấp", "Hữu ích trong trường hợp khẩn cấp"],
  ["Dành cho trẻ em", "Dành cho người lớn"],
  ["Khôn ngoan", "Thông minh"],
  ["Dễ làm", "Khó làm"],
  ["Vô giá trị", "Vô giá"],
  ["Tự nhiên", "Nuôi dưỡng"],
  ["Chế độ độc tài", "Dân chủ"],
  ["Lời chào thông thường", "Lời chào kỳ quặc"],
  ["Tên chó", "Tên mèo"],
  ["Không đảng phái", "Đảng phái"],
  ["Hạn chế", "Vô hạn"],
  ["Sự kiện bình dị", "Sự kiện trang trọng"],
  ["Đầu tư tồi", "Đầu tư tốt"],
  ["Nói chuyện phiếm", "Chủ đề nặng"],
  ["Nhẹ", "Cay"],
  ["Tôn giáo", "Phản tôn giáo"],
  ["Không phải là nghệ thuật", "Là nghệ thuật"],
  ["Bất hợp pháp", "Cấm"],
  ["Phổ biến", "Có tính độc quyền"],
  ["Mất kiểm soát", "Kiểm soát"],
  ["Im lặng", "Ồn ào"],
  ["Pokemon không gợi cảm", "Pokemon gợi cảm"],
  ["Bí mật", "Thông tin công khai"],
  ["Quá nhỏ", "Quá lớn"],
  ["Ngắn", "Dài"],
  ["Năm tồi tệ nhất trong lịch sử", "Năm tốt nhất trong lịch sử"],
  ["Xã hội chủ nghĩa", "Chủ nghĩa tư bản"],
  ["Sự thật ít được biết đến", "Sự thật được biết rộng rãi"],
  ["Tĩnh", "Động"],
  ["Vấn đề địa phương", "Vấn đề toàn cầu"],
  ["Tài năng", "Kỹ năng"],
  [
    "Thời đại tồi tệ nhất để đi du lịch thời gian",
    "Thời đại tốt nhất để đi du lịch thời gian",
  ],
  ["Tệ nhất", "Tốt nhất"],
  ["Con số nhỏ", "Con số lớn"],
  ["1", "0"],
  ["Cổ điển", "Hiện đại"],
  ["Từ xấu xí", "Từ đẹp"],
  ["Nhỏ", "Siêu nhỏ"],
  ["Không tự nhiên", "Tự nhiên"],
  ["Người chân thật", "Người giả dối"],
  ["Thuộc loại bản sao", "Sáng tạo"],
  ["Nghi thức", "Phép lịch sự"],
  ["Màu không gợi cảm", "Màu gợi cảm"],
  ["Lợi ích cho bạn", "Lợi ích cho mọi người"],
  ["Vô năng", "Mạnh mẽ"],
  ["Không hút thuốc vape", "Hút thuốc vape"],
  ["Trái cây", "Rau củ"],
  ["Khoa học", "Giả khoa học"],
  ["Chủ đề hài hước", "Chủ đề nghiêm túc"],
  ["Mềm", "Chắc"],
  ["Sở thích đáng cười", "Thật sự tệ"],
  ["Tin đồn", "Tin tức"],
  ["Khó ngồi", "Dễ ngồi"],
  ["Không đủ", "Quá nhiều"],
  ["Ngang", "Dọc"],
  ["Không mùi", "Có mùi"],
  ["Dễ ôm", "Không dễ ôm"],
  ["Khác nhau", "Giống nhau"],
  ["Bao hàm", "Loại trừ"],
  ["Giống chó tệ", "Giống chó tốt"],
  ["Nghệ thuật", "Thương mại"],
  ["Một hit wonder", "Biểu tượng pop"],
  ["Lời khuyên tệ", "Lời khuyên tốt"],
  ["Đi tick", "Đi tock"],
  ["Kẹo tệ", "Kẹo ngon"],
  ["Truyền thống", "Cực đoan"],
  ["Cảm giác xấu miệng", "Cảm giác tốt miệng"],
  ["Bất hợp pháp", "Hợp pháp"],
  ["Suy nghĩ sâu", "Suy nghĩ nông"],
  ["Trường tệ", "Trường tốt"],
  ["Không bao giờ đúng giờ", "Luôn đúng giờ"],
  ["Sẽ không sống đến 100 tuổi", "Sẽ sống đến 100 tuổi"],
  ["Nhân vật Disney xấu", "Nhân vật Disney đẹp"],
  ["Tương tự", "Giống hệt nhau"],
  ["Tổng thống tệ", "Tổng thống tốt"],
  ["Kì lạ", "Lạ lùng"],
  ["Nổi tiếng", "Nổi danh"],
  ["Thần yếu nhất", "Thần mạnh nhất"],
  ["Người buồn tẻ", "Người vui vẻ"],
  ["Sách bị đánh giá thấp", "Sách bị đánh giá cao"],
  ["Sự hiểu biết thông thường", "Niềm tin ngoại vi"],
  ["Việc làm tệ nhất", "Việc làm tốt nhất"],
  ["Loài đang bị đe dọa", "Loài đang quá đông dân"],
  ["Màu xanh lam", "Màu xanh lá cây"],
  ["Mạo hiểm", "Kinh hoàng"],
  ["Nhà khoa học máy tính", "Vận động viên"],
  ["Mong đợi", "Không mong đợi"],
  ["Người bạn có thể đánh bại", "Người sẽ đánh bại bạn"],
  ["Nỗi sợ không hợp lý", "Nỗi sợ hợp lý"],
  ["Trò chơi bị đánh giá thấp", "Trò chơi bị đánh giá cao"],
];

1;
